version: '3.7'
services:
  chat_api:
    build:
      context: .
    env_file:
      - .env.dev
    image: api_img
    container_name: chat_api
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - chat_data
      - redis
  chat_data:
    image: postgres:latest
    container_name: chat_data
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: chat_redis
    ports:
      - "6379:6379"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgdata:
    driver: local
  pgadmin-data:
    driver: local
